sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
# keep the npm cache to speed up installs
cache:
  yarn: true
  directories:
  - "$HOME/.npm"

script:
  - yarn build
  - yarn test:unit
  - yarn test:lint
  - yarn test:nsp
